-- ============================================
-- Seed Data for Sports Registration System
-- ============================================

-- Insert sample colleges
INSERT INTO colleges (name, short_name, city) VALUES
    ('Indian Institute of Technology Delhi', 'IIT Delhi', 'New Delhi'),
    ('Indian Institute of Technology Bombay', 'IIT Bombay', 'Mumbai'),
    ('Indian Institute of Technology Madras', 'IIT Madras', 'Chennai'),
    ('Delhi University', 'DU', 'New Delhi'),
    ('Jawaharlal Nehru University', 'JNU', 'New Delhi'),
    ('BITS Pilani', 'BITS', 'Pilani'),
    ('National Institute of Technology Karnataka', 'NITK', 'Surathkal'),
    ('Vellore Institute of Technology', 'VIT', 'Vellore'),
    ('SRM Institute of Science and Technology', 'SRM', 'Chennai'),
    ('Manipal Institute of Technology', 'MIT', 'Manipal');

-- Insert sample sports
INSERT INTO sports (name, sport_code, category, description, rules, is_team_event, team_size_min, team_size_max, fees, registration_start, registration_deadline, schedule_start, venue, max_participants, is_registration_open) VALUES
    (
        'Cricket',
        'CRI',
        'outdoor',
        'T20 format cricket tournament with exciting matches and great prizes.',
        '1. Each team must have 11 players\n2. T20 format - 20 overs per side\n3. Standard ICC rules apply\n4. Decision of umpires is final',
        true,
        11,
        15,
        500.00,
        now() - interval '1 day',
        now() + interval '30 days',
        now() + interval '35 days',
        'Main Cricket Ground',
        16,
        true
    ),
    (
        'Football',
        'FOO',
        'outdoor',
        '5-a-side football tournament. Fast-paced action guaranteed!',
        '1. Teams of 5 players each\n2. 20 minutes per half\n3. No offside rule\n4. Rolling substitutions allowed',
        true,
        5,
        7,
        300.00,
        now() - interval '1 day',
        now() + interval '25 days',
        now() + interval '30 days',
        'Football Field A',
        20,
        true
    ),
    (
        'Badminton Singles',
        'BAD',
        'indoor',
        'Individual badminton championship. Show your skills!',
        '1. Best of 3 games\n2. Each game to 21 points\n3. BWF rules apply\n4. Players must bring their own rackets',
        false,
        1,
        1,
        150.00,
        now() - interval '1 day',
        now() + interval '20 days',
        now() + interval '25 days',
        'Indoor Sports Complex',
        32,
        true
    ),
    (
        'Badminton Doubles',
        'DBL',
        'indoor',
        'Team up and dominate the court!',
        '1. Best of 3 games\n2. Each game to 21 points\n3. BWF rules apply\n4. Players must bring their own rackets',
        true,
        2,
        2,
        200.00,
        now() - interval '1 day',
        now() + interval '20 days',
        now() + interval '25 days',
        'Indoor Sports Complex',
        24,
        true
    ),
    (
        'Table Tennis',
        'TTE',
        'indoor',
        'Singles table tennis tournament. Precision and speed!',
        '1. Best of 5 games\n2. Each game to 11 points\n3. ITTF rules apply',
        false,
        1,
        1,
        100.00,
        now() - interval '1 day',
        now() + interval '15 days',
        now() + interval '20 days',
        'Table Tennis Hall',
        48,
        true
    ),
    (
        'Chess',
        'CHE',
        'indoor',
        'Classical chess tournament. Outsmart your opponents!',
        '1. 30 minutes per player\n2. FIDE rules apply\n3. Touch-move rule enforced',
        false,
        1,
        1,
        50.00,
        now() - interval '1 day',
        now() + interval '20 days',
        now() + interval '25 days',
        'Conference Room B',
        64,
        true
    ),
    (
        'Valorant',
        'VAL',
        'esports',
        '5v5 Valorant tournament. May the best team win!',
        '1. Best of 3 maps\n2. Standard competitive rules\n3. Teams must have 5 players\n4. Substitutes allowed',
        true,
        5,
        6,
        400.00,
        now() - interval '1 day',
        now() + interval '25 days',
        now() + interval '30 days',
        'Esports Arena',
        16,
        true
    ),
    (
        '100m Sprint',
        'SPR',
        'athletics',
        'The classic 100 meter dash. Who is the fastest?',
        '1. Standard athletics rules\n2. Spikes allowed\n3. False start results in disqualification',
        false,
        1,
        1,
        75.00,
        now() - interval '1 day',
        now() + interval '10 days',
        now() + interval '15 days',
        'Athletics Track',
        50,
        true
    ),
    (
        'Long Jump',
        'LJU',
        'athletics',
        'Test your jumping prowess!',
        '1. 3 attempts per participant\n2. Best jump counts\n3. Standard athletics rules',
        false,
        1,
        1,
        75.00,
        now() - interval '1 day',
        now() + interval '10 days',
        now() + interval '15 days',
        'Athletics Ground',
        40,
        true
    ),
    (
        'Basketball 3x3',
        'BAS',
        'outdoor',
        '3-on-3 basketball street style!',
        '1. 10 minute games\n2. First to 21 or highest score wins\n3. FIBA 3x3 rules apply',
        true,
        3,
        4,
        250.00,
        now() - interval '1 day',
        now() + interval '20 days',
        now() + interval '25 days',
        'Basketball Court',
        20,
        true
    );

-- Note: Admin user should be created via the signup flow and then manually promoted
-- UPDATE profiles SET role = 'admin' WHERE email = 'admin@sportsfest.com';
